FROM debian:stretch-slim

# Orig source:
# https://github.com/docker-library/php

# Reference:
# 如何在 Debian Stretch 中安装使用 PHP5
# https://www.debian.cn/archives/1511
# latest apache package
# https://packages.debian.org/search?keywords=apache2

# dependencies required for running "phpize"
# (see persistent deps below)
ENV PHPIZE_DEPS \
		autoconf \
		dpkg-dev \
		file \
		g++ \
		gcc \
		libc-dev \
		make \
		pkg-config \
		re2c

# persistent / runtime deps
RUN apt-get update && apt-get install -y \
		$PHPIZE_DEPS \
		ca-certificates \
		curl \
		libcurl3 \
		xz-utils \
	--no-install-recommends && rm -r /var/lib/apt/lists/*

# Install apache 2.4.33
RUN cp /etc/apt/sources.list /etc/opt/sources.list.orig
RUN echo "deb http://cdn-fastly.deb.debian.org/debian buster main contrib non-free"  >> /etc/apt/sources.list
RUN apt-get update \
	&& apt-get install -y --no-install-recommends \
		apache2 \
	&& rm -rf /var/lib/apt/lists/*
#RUN mv /etc/opt/sources.list.orig /etc/opt/sources.list

# Install php5.6
RUN apt-get update; \
    apt-get install -y apt-transport-https lsb-release ca-certificates wget
RUN wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg; \
    echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php5.list
RUN apt-get update; \
    apt-get install -y php5.6 php5.6-mysql \
           php5.6-xml php5.6-zip php5.6-json \
           php5.6-gd php5.6-bcmath \
           php5.6-mbstring \
   libcurl4
#    php5.6-common 
#   php5.6-curl

# Force install php5.6-curl
# https://packages.sury.org/php/pool/main/p/php5.6/php5.6-curl_5.6.36-1%2B0~20180505045928.13%2Bstretch~1.gbp9b5cab_amd64.deb
COPY php5.6-curl.deb /tmp/php5.6-curl.deb
RUN dpkg -i --ignore-depends=libcurl3 /tmp/php5.6-curl.deb
RUN phpenmod curl
#RUN apt-get update ; \
    #    apt-get install -y \
    #    php5.6-curl libcurl3

# DEL??
RUN /usr/sbin/a2dismod mpm_event && /usr/sbin/a2enmod mpm_prefork
COPY docker-php-ext-* docker-php-entrypoint /usr/local/bin/


ENTRYPOINT ["docker-php-entrypoint"]
COPY apache2-foreground /usr/local/bin/
WORKDIR /var/www/html
EXPOSE 80
CMD ["apache2-foreground"]
